const popular = [
    {
        id: 10,
        name: 'Vagabond',
        capa: 'https://img.mangaschan.com/uploads/manga-images/v/vagabond/thumbnail.jpg',
        score: 8.8,
        status: 'Em curso',
        type: 'Manga',
        date: 1999,
        author: 'Inoue Takehiko',
        chapters: 327,
    },
    {
        id: 11,
        name: 'Berserk',
        capa: 'https://mangaschan.net/wp-content/uploads/Berserk-Mangaschan.jpg',
        score: 9.0,
        status: 'Em curso',
        type: 'Manga',
        date: 1989,
        author: 'MIURA Kentaro',
        chapters: 375,
    },
    {
        id: 12,
        name: 'Prey',
        capa: 'https://img.mangaschan.net/uploads/manga-images/p/prey/thumbnail.webp',
        score: 9.0,
        status: 'Em curso',
        type: 'Manhwa',
        date: 2019,
        author: 'MIURA Kentaro',
        chapters: 14,
    },
    {
        id: 13,
        name: 'Kill the Dragon',
        capa: 'https://mangaschan.net/wp-content/uploads/Kill-the-Dragon-Mangaschan.webp',
        score: 7.0,
        status: 'Em curso',
        type: 'Manhwa',
        date: 2022,
        author: 'Redice Studio',
        chapters: 91,
    },
    {
        id: 14,
        name: 'I’m an Ex-class Hunter',
        capa: 'https://img.mangaschan.net/uploads/manga-images/i/im-an-ex-class-hunter/thumbnail.webp',
        score: 7.0,
        status: 'Em curso',
        type: 'Manhwa',
        date: 2023,
        author: '-',
        chapters: 33,
    },
    {
        id: 15,
        name: 'Naruto',
        capa: 'https://img.mangaschan.com/uploads/manga-images/n/naruto/thumbnail.jpg',
        score: 8.0,
        status: 'Completo',
        type: 'Manga',
        date: 1999,
        author: 'Kishimoto Masashi',
        chapters: 700,
    },
]

export default popular