// eslint-disable-next-line import/no-anonymous-default-export
export default{
    title: 'dark',
    background: "#171717",
    color: {
      font: "#000000",
      primary: "#ED274A",
      icon: "#ED274A",
      blue: "#6699ff",
      secundary: "#FF620A",
      escuro: "#0D2818",
      bar: "#999",
      outlined: '#853EF3',
      activity: '#B6B6B6',
      price: '#27AE60',
      light: '#FFFFFF',
      blue: "#0092FF",
      red: "#EB5757",
      green: "#27AE60",
      text: "#333333",
      black: "#000000",
      title: "#FFFFFF",
      t2: "#000",
      t3: "#EFFCCE",
      t4: '#FF8360',
      label: "#cccccc",
      off: "#262626",
      off2: "#404040",
      off3: "#595959",
      background: "#171717",
      background2: "#1d1d1d",
      rare: '#9DACFF',
      lendary: '#3454D1',
      premium: {
        bg: "#E0CA3C",
        label: "#E9D972",
        title: "#FFF"
      },
    },
    size: {
      label: '1.125em',
      title: '1.5em',
      headtitle: '2em',
      sublabel: '1em',
    },
    font: {
      extrabold: "Products_BoldExtra",
      bold: "Font_Bold",
      bold_italic: "Products_Bold_Italic",
      medium: "Font_Medium",
      medium_italic: "Products_Medium_Italic",
      book: "Font_Book",
      book_italic: "Products_Book_Italic",
  
      mmedium: "Manga_Medium",
      mbold: "Manga_Bold",
      mitalic: "Manga_Italic",
    },
    opacity: {
      dez: "#fffffff",
      oito: "#FFFFFF80",
      seis: "#FFFFFF60",
      quatro: "#FFFFFF40",
      dois: "#FFFFFF20",
    },
    padding: {
      top: 60,
    }
    
  }