export const mangas = [
    {
        name: 'Jujutsu Kaisen',
        capa: 'https://i0.wp.com/animebox.net/wp-content/uploads/2022/11/jujutsu-kaisen-manga-volume-21.webp?resize=640%2C1007&ssl=1',
        score: 7.6,
        status: 'Em curso',
        type: 'Manga',
        date: 2018,
        author: 'AKUTAMI Gege',
        chapters: 247,
    },
    {
        name: 'Osananajimi no Ijou Kawaii Imouto-chan',
        capa: 'https://kenmei.b-cdn.net/covers/manga_series/67519/cover/jpeg-thumbnail-large-cbf91a8fd313d12c69e8b7de96dca8b0.jpeg',
        score: 7.2,
        status: 'Em curso',
        type: 'Manga',
        date: 2023,
        author: 'Fuyujima Kure',
        chapters: 3,
    },
    {
        name: 'Ijiranaide, Nagatoro-san',
        capa: 'https://pbs.twimg.com/media/F_6RdXXX0AAml_2?format=jpg&name=large',
        score: 7.4,
        status: 'Em curso',
        type: 'Manga',
        date: 2017,
        author: '774 house',
        chapters: 141,
    },
    {
        name: 'Hajimete no Gal',
        capa: 'https://img.mangaschan.com/uploads/manga-images/h/hajimete-no-gal/Hajimete%20no%20Gal%20mangaschan.webp',
        score: 7.2,
        status: 'Em curso',
        type: 'Manga',
        date: 2020,
        author: 'Ueno Meguru',
        chapters: 176,
    },
    {
        name: 'Kono Subarashii Sekai ni Shukufuku wo!',
        capa: 'https://img.mangaschan.com/uploads/manga-images/k/kono-subarashii-sekai-ni-shukufuku-wo/thumbnail.jpg',
        score: 7.2,
        status: 'Em curso',
        type: 'Manga',
        date: 2014,
        author: 'Akatsuki Natsume',
        chapters: 84,
    },
    {
        name: 'Ban Sheng Nu Tanpaile – The Saintess Has a Showdown',
        capa: 'https://img.mangaschan.com/uploads/manga-images/b/ban-sheng-nu-tanpaile-the-saintess-has-a-showdown/thumbnail.webp',
        score: 7.0,
        status: 'Em curso',
        type: 'Manga',
        date: 2021,
        author: 'Bunny',
        chapters: 4,
    },

]